#+TITLE: TFLite Interpreter

A small program for loading a ~.tflite~ file and inspecting it in a programmatic
way using python. See ~model.py~ for a better explanation.

Files in the ~tflite~ directory was generated by Google's ~flatc~ program using
the schema from the Tensorflow repo. [[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/schema.fbs][Link.]]

** Usage

   The parser requires Google's [[https://google.github.io/flatbuffers/][flatbuffer]] library. Installation instructions
   can be found [[https://google.github.io/flatbuffers/flatbuffers_guide_building.html][here]]. After installation, its just a matter of installing the
   Python library (using ~pip install flatbuffers~ or something similar).

** Supported models

   I've only tested it with a Mobile Nets V2 model. Specifically the one called
   ~Mobilenet_V2_1.0_224_quant~ located [[https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models.md#image-classification-quantized-models][here.]]

   It should be fairly easy to add support for parsing more different
   operations. See the comments in ~model.py~.

** What's missing
   - Implementing the intepreter for the different operations (Conv2D, Add,
     etc).
   - Testing with different models.
